### ISSUE TITLE
Worksite / Sector Layer

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#140]
CA-RTF7 suggested that we should have a "worksite layer" which would be used like segments to track building or groups of building search progression. This would be used more like INSARAG ICMS Workflow. 

We need to discuss this as a group. 

Should we just keep using Segments? Or create new layer?

**Comment by CLivingstone** [comment]
Using the segments layer for worksites works for now, but ultimately I think it will be confusing. In an event like an earthquake we would end up using the segments layer for both typical segments and worksites occurring within segments.  And in other cases, like the Surfside collapse, it may make sense to have segments within a worksite.

I would probably recommend creating a separate worksite layer.  Or, we could potentially add "worksite" as an additional designation in the Operational Areas layer.  Worksite status could be reflected in the popup, or we could create a worksite status layer view to symbolize worksite progress.

**Comment by pjdohertygis** [comment]
Let's raise with the Cadre this winter, in particular USA-1 and USA-2.
