### ISSUE TITLE
Error adding AGOL hosted items to ArcGIS Pro

### ISSUE THREAD

**Issue by grover556** [pjdohertygis/SARCOP#151]
Having a consistent and repeatable issue when I try to add a hosted service to a map in ArcGIS Pro (2.8.1). When using Add Data and selecting the item from the Portal, I get an error "Failed to add data: https://xxxxxxx/MapServer". However, when I view the service on AGOL, click View, and paste the URL (with token) into the Add Data from Path dialog, the service is added just fine.

Example service:
https://fema.maps.arcgis.com/home/item.html?id=de1f0894a7cd4e7886ca6558d2c6436b

**Comment by pjdohertygis** [comment]
@grover556 I believe I have seen this issue but it is not consistent. Let's ask Tim NY-TF1or Esri if they are seeing this too.

**Comment by pjdohertygis** [comment]
I believe this is now fixed - closing.
