### ISSUE TITLE
One Waypoint, Many Observations

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#186]
Jason from MO-TF1 raised the topic "One Waypoint, Many Observations". The idea being if you are at a structure, could you simply add on waypoint for that building, then add information for 

- Human Interactions (Rescue, Victims / HR, etc)
- Damage 
- Hazards
- Other 

That one entry would capture all the pertinent information for all 4 waypoints and presumably fill out a search marking symbol. 

Example: TAK WASP Plug-in https://youtu.be/9NYIbM9JwvI

Pros: Fewer data points, potentially less clicks depending on how it is configured
Cons: It is not clear how data would be stored and symbolized, requires a data model overhaul for our wide area search form, potentially MORE clicks when trying to do something simple. 

**Questions**
- What are the benefits/drawback for collecting data this way? Would it be faster in the field? What decisions would it enable? 
- What app would we use to accomplish this? QuickCapture wouldn't work - Survey123 vs Field Maps? 

Feel free to add comments and perspective below. I don't anticipate we will implement this in 2022, but something to consider for 2023.

**Comment by jwarzinik** [comment]
The part of WASP that we don't have yet is a way to digitally document the info from the structure search marking sticker that we leave behind.   I will try to dig into the ATAK DB and see if I can see the schema they are using for storage.

![20211206_150926](https://user-images.githubusercontent.com/91565740/144924574-3f331b3b-2047-4e68-ac25-b6aaea445bb0.jpg)

**Comment by pjdohertygis** [comment]
@jwarzinik maybe in the short-term we define this in the Rules of Engagement - "take photo of search marking". I'd hate to add more data collection burden onto folks if no one is going to use the data for decision making.

**Comment by grover556** [comment]
Is this something we are having issues with from IST or AHJ, or is the desire just to capture what's written on the marking?
