### ISSUE TITLE
[ENH] - Field Maps "Favorites" - TF Edit & Field Maps Repeat Information Feature request.

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/SARCOP#235]
TF Edit & Field Maps Repeat Information; Would be convenient to have local entry cached similar to Intel Manager 1.0 for Team and Operator Name and maybe Squad ID?

**Comment by pjdohertygis** [comment]
@KeithJGw agreed, this is a current limitation of Field Maps - there is no "Favorites" like Survey123 or Project User Inputs like in QuickCapture. Can you search around in the Esri Community and see if this is already an ArcGIS Idea? If so we can add comments on why it is needed, if not we can add a new Idea.

**Comment by pjdohertygis** [comment]
For reference.... this capability has a different name for each application below, but same general premise, I don't want to enter in my Team and Name over and over again. 

Survey123 = Favorites
QuickCapture = Project User Inputs
Web AppBuilder - Smart Editor - Smart Actions - Presets

QuickCapture
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/e441e647-1699-43ec-b684-95982ef230bb)


Web AppBuilder
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/a69cdcb0-3941-4c6d-a480-b6bfefdc563e)

**Comment by pjdohertygis** [comment]
@avezina do you know if this capability described in the thread is on the road map for Smart Forms in general?

**Comment by avezina** [comment]
No clear plans around this yet, it's under discussion. Similar functionality can be found in Pro where attributes can be prompted and updated for newly created features.
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/50338557/38267d22-b249-4b1d-b220-58524db4433c)
Best bet is this could make it in along with feature template functionality in Online, in the future.

**Comment by pjdohertygis** [comment]
It looks like with a little Arcade we can use the "filter" method.

End user would:
1) Set Team Name Filter
2) Use Smart Form to add new waypoints, the Team Name set in the filter should be applied 

See blog below @jdokemaps 
https://community.esri.com/t5/arcgis-experience-builder-blog/use-the-filtered-value-as-a-default-field-value/ba-p/1365021

**Comment by pjdohertygis** [comment]
Closing and merging with https://github.com/pjdohertygis/SARCOP/issues/289
