### ISSUE TITLE
[BUG] -  QuickCapture Landscape Mode issue with Tripltek 9 Pro 93

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#241]
### Which app?

QuickCapture

### Describe the Device, Operating System, and Browser

Tripltek 9 Pro 93 https://www.tripltek.com/product-page/tripltek9
Android v12
QuickCapture v1.18.93

### Describe the bug
 
In landscape you do not get the split screen capability of map and symbols.

### Expected Behavior

Rotate seemlessly between landscape and portrait mode on all devices. 

### Reproduction Steps & Sample

Install QuickCapture on Tripltek 9 Pro 93
Use any project with the map side-by-side mode enabled 
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/4256979/3ed3e109-c4e0-4552-9d40-28173b22b22e)

Rotate the tablet 

### Other Relevant Info

N/A

### Priority impact

p0 - not time sensitive

### Impact

This makes QuickCapture cumbersome to use for MO-TF1 that is using this ruggedized device. They can still collect data but in the field there are times when rotating the tablet to portrait is easier.

**Comment by pjdohertygis** [comment]
This has been sent along to the QuickCapture Team, just documenting on Git so we can track it.

**Comment by pjdohertygis** [comment]
Made a correction to the above - according to Les at MO-TF1 

"Correct In landscape you do not get the split screen capability of map and symbols."

**Comment by jwarzinik** [comment]
Any update on better support for split screen on Android devices? Works great on a full sized iPad and iPad mini4 with a 2048 x 1536 screens but not on our newer Tripltek 8 2560x1600 screen.
![image](https://github.com/pjdohertygis/WideAreaSearchTemplates/assets/91565740/89c8985e-4c62-4a01-b935-10a7ce88a85c)

**Comment by JohnHasthorpe** [comment]
@jwarzinik - I have requested some information about reported device dimensions from @pjdohertygis and aim to purchase one of these devices to facilitate future testing.

**Comment by JohnHasthorpe** [comment]
This should now be addressed @pjdohertygis
