### ISSUE TITLE
[BUG] -  Quickcapture on Samsungs, "Back" button causes unexpected behavior.

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#256]
### Which app?

QuickCapture

### Describe the Device, Operating System, and Browser

Samsung Android, limited details. 

### Describe the bug

Original description 
"RST QC on droid OS, when user selected the back key then edit, this created a duplicate RST waypoint. Cell service was poor. I couldn’t duplicate this issue on my iPhone unfortunately.

I watched it with my own eyes.  We had spotty cell service…  In QC RST the droid user noticed a mistake before submitting the project then chose the back (<) “button” at the bottom of the screen to edit.  Only droid OS phones have this option, my iPhone app didn’t have a back option.  When he made the edit, two waypoints were submitted, one with the original or mistake info and one with the corrected info.  I couldn’t confirm with another droid phone users.  Really strange behavior."

We did a little digging and think it was this built in back button, not something within the QuickCapture interface.
![image](https://github.com/pjdohertygis/SARCOP/assets/4256979/9e7a6390-f293-410c-9706-aab1da5a6762)

### Expected Behavior

At a minimum, the end user would expect the back button to behavior similarly to the Back button in QuickCapture. In this case it sounds like it might have somehow added a point? 

### Reproduction Steps & Sample

1. Open up QuickCapture on a Samsung phone, you can use our project https://arcg.is/1L9KeK
![image](https://github.com/pjdohertygis/SARCOP/assets/4256979/91dbc69d-656e-4678-b283-c23c92b4854b)
2. Enter a point (RST), "make a mistake" 
3. Then choose the back (<) “button” at the bottom of the screen to edit
4. Enter another point
5. Did it add one or two points? Did it do what you expected?

### Other Relevant Info

We will try to get more information on this. 

### Priority impact

p0 - not time sensitive

### Impact

It could be confusing for the end user, although this is the first time we've been notified about it so unsure how common it is.

**Comment by JohnHasthorpe** [comment]
I think the issue happens when the user presses the android back button when the user is in the map (used to review the captured location).

We should give the option to discard the feature if they do this. I'll create an issue for this one.

**Comment by pjdohertygis** [comment]
Again on 07/16 from Dave Weber "3.	QC RST issues:
a.	We ran into the droid OS back button causing issues again.  I was able to simply instruct the user to not use the OS back and only navigate in the esri app.  I guess only engineers have this issue, but I am surprised it hasn’t come up for others during WAS workspace use.

**Comment by oviera-napsg** [comment]
Documented - no additional errors reported from users.  Awaiting next StS training in Oct. 2024 for any additional Android users to report their experience via D. Weber.
