### ISSUE TITLE
[BUG] -  QC Battery Drainage with Location Sharing Tracks

### ISSUE THREAD

**Issue by jdokemaps** [pjdohertygis/SARCOP#269]
### Which app?

QuickCapture

### Describe the Device, Operating System, and Browser

Galaxy S22 Ultra
SM-S908U
ArcGIS QuickCapture App version: 1.19.15

### Describe the bug

Report from Heather Anesta (hanesta@responsesystem.org)

### Expected Behavior

When I have QC open on my phone, even if not on my screen as the main app, my battery depleted about 5x faster than usual. As a result, I couldn't have QC open unless I was plugged in. This affected my ability to utilize markings to their full, real-time potential on site. Any way to help create some battery usage limitations for QC so that we can fully utilize QC in field?

### Reproduction Steps & Sample

May be reproducible if location sharing tracks are turned back on in the QC project. 

### Other Relevant Info

This may have been due to Location Sharing tracks being turned on in the QC project.

### Priority impact

p0 - not time sensitive

### Impact

This affected my ability to utilize markings to their full, real-time potential on site.

**Comment by pjdohertygis** [comment]
Closing this for now as we don't have a fix.
