### ISSUE TITLE
[ENH] - Intel Manager 2.0 Search By ObjectID

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#273]
### Which app?

Intel Manager 2.0 (Experience Builder)

### Describe requirements

Allow end user to switch from searching for an address / place in the search widget to searching for ObjectID in the waypoint layer. 

### Alternatives

None

### Priority impact

p1 - time sensitive

### Impact

This will help end users find unique waypoints and quickly make edits to them. Consider doing this for RST as well.

**Comment by pjdohertygis** [comment]
Paul started, Adam will finish!

**Comment by afackler** [comment]
Looks like it is working as intended, I did change the title in the search from just Waypoints to SARCOP Waypoints to help categorize things, also added waypoint type to the search result (See below)

![image](https://github.com/pjdohertygis/SARCOP/assets/55416740/57ee35eb-2909-4803-8976-bb5f3d6067d5)
![image](https://github.com/pjdohertygis/SARCOP/assets/55416740/f935fa5e-ee94-432d-8435-e89dbaa657f5)

One limitation I still need to see if I can fix is selecting the waypoint/ hitting enter will only bring up the pop-up and highlight the point, but it will not zoom into the point.

![image](https://github.com/pjdohertygis/SARCOP/assets/55416740/76a888ff-be04-4cfd-83c5-3c924f39c825)

**Comment by pjdohertygis** [comment]
@afackler Test it out now, I think I fixed it by using Action - Record Selection 

![image](https://github.com/user-attachments/assets/9d8fca41-797b-40e0-82ff-d4e7e0ada828)

**Comment by pjdohertygis** [comment]
Something we will want to highlight in our training video is that if you 
1) Start an "editing session" by opening the widget
2) Then search for an ObjectID
3) It will automatically open the form 

![image](https://github.com/user-attachments/assets/830cd3bd-cbd3-495a-ad7e-b3557d99631c)

**Comment by pjdohertygis** [comment]
It appears this is implemented in the Sandbox and will follow up with Deployment. Closing issue.
