### ISSUE TITLE
[ENH] - Intel Manager 2.0 Measure Tool

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#276]
### Which app?

Intel Manager 2.0 (Experience Builder)

### Describe requirements

Implement and test out the built-in measure tool within Experience Builder Map widget 

![image](https://github.com/pjdohertygis/SARCOP/assets/4256979/1e7f12fd-fece-4026-b5c3-38b522e3d24d)

### Alternatives

None

### Other Relevant Info

Doc: https://doc.arcgis.com/en/experience-builder/latest/configure-widgets/map-widget.htm

### Priority impact

p0 - not time sensitive

### Impact

This is an easy-to-use tool that allows people to make quick measurements on the map.

**Comment by emontague-napsg** [comment]
The measure tool within Experience Builder Map widget offers the ability to measure a distance (drawing a line) or measure area (drawing a polygon). You can switch between units while measuring. One thing different from the Web App Builder measure widget is "measuring" a point which provides the coordinates of the point. This capability is provided by the coordinate conversion widget, so I believe the measure tool is sufficient.
