### ISSUE TITLE
[ENH] - Intel Manager 2.0 Coordinate Conversion Tool 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#277]
### Which app?

Intel Manager 2.0 (Experience Builder)

### Describe requirements

Implement and test the use of the Coordinate Conversion widget in Experience Builder / Intel Manager 2.0
![image](https://github.com/pjdohertygis/SARCOP/assets/4256979/76be5a98-aaf6-40cc-9a40-2e51fcea78a9)

Is it working as expected? Any coordinate notation formats we can remove / not needed?

### Alternatives

None

### Other Relevant Info

Doc: https://doc.arcgis.com/en/experience-builder/latest/configure-widgets/coordinate-conversion-widget.htm

### Priority impact

p0 - not time sensitive

### Impact

This is an easy to use tool for converting between different coordinate notation systems.

**Comment by emontague-napsg** [comment]
The Coordinate Conversion widget in ExB does have the ability to (1) place a point for a coordinate input and (2) has a button to zoom to coordinate input.


1.
![image](https://github.com/pjdohertygis/SARCOP/assets/121051642/69846a11-d5f7-4faa-b5b5-a37f92a157a9)


2.
![image](https://github.com/pjdohertygis/SARCOP/assets/121051642/22cef1d7-b1c2-44b8-8de7-7b7c4569c26d)

**Comment by pjdohertygis** [comment]
Configured
