### ISSUE TITLE
[BUG] -  Android phone got hot while running QuickCapture / tracklog and while taking pics out of app

### ISSUE THREAD

**Issue by KeithJGw** [pjdohertygis/SARCOP#279]
### Which app?

QuickCapture

### Describe the Device, Operating System, and Browser

7/4/2024 Samsung Galaxy A53, Android 14 One UI Version 6.2, QuickCapture 1.19.15, SARCOP Sandbox Workspace 6/25/2024, WiFi Off, Precise Location On for Google, QuickCapture, Field Maps, and GPS for photos..

Earlier report from FEMA Blue IST Structure Specialist 
Hi Paul,

When I have QC open on my phone, even if not on my screen as the main app, my battery depleted about 5x faster than usual. As a result, I couldn't have QC open unless I was plugged in. This affected my ability to utilie markings to their full, real-time potential on site. Any way to help create some battery usage limitations for QC so that we can fully utilize QC in field?

Thanks!

Below are the specs you requested

Galaxy S22 Ultra
SM-S908U
ArcGIS QuickCapture App version: 1.19.15

### Describe the bug

Phone got hot causing video stutter / lag on short clips and camera failures.
I've tried to crash QuickCapture by taking photos in and out of app and successfully crashed QC on several occasions.
This time I noticed that my phone was getting quite hot and causing two short video clips to stutter / lag and camera failure when trying to take pics out of QC several times.
Thought it was due to local temperature of 92 degrees and using QC and camera at the same time.
Have done this workflow before, but not gotten phone real hot and camera errors previously.
Turned off QC and let the phone cool. Restart QC track log and taking pics out of app it didn't take long for the phone to get hot again.
I nearly discounted the issue thinking it was due to local heat and QC and photos out of app at the same time yet tweeted about it. "QuickCapture is using a lot of CPU and overheating my phone.
Also causing lag when trying to record short videos.
Haven't noticed this before."
Dr Doherty replied to add to GitHub due to "one Android device with those symptoms on NM deployment."
I take screenshots of phone for notation and recollection during my tests.
I edit track log crashes to Damage Observation later for contrast in Intel manager.

### Expected Behavior

Stable temperature or slight to moderate increase in device temperature due to usage of QC and camera taking pics in and out of app.
Not expecting my phone to get so hot that recording two short video clips have stutter / lag in the video and repeated camera failures.

### Reproduction Steps & Sample

1 Open QC & map zoom out then close map to cache basemap.
2 Start tracklog enter waypoints with photo and take photos out of app.
3 Phone got hot quickly. Have noticed increase in temperature while running QC track log previously, but not as severe as this time.

### Other Relevant Info

Tracklogs via vehicle and on foot. Changed some track log types on the fly.
Tracklogs and waypoints with photos, and photos and short video clips out of app.
Issues; Phone gets hot. Causing video stutter / lag on short clips and camera failures.
After turning QC off and letting the phone cool, it crashed once on a very short track log with no way point or photos taken.

12:14 PM Open QC and map zoom out, signal 4 bars, battery 100% 
12:41 Hasty signal 5 bars, battery 97% End Time 12:53 PM change tracklog type
12:53 Primary End Time 1:10 PM

Situation Update 7/4/2024 12:56 PM with photo in app, and one photo out of app.
1:00 PM Phone hot. Record video of 0:35 sec has stutter / lag
1:10 End track log and turn QC off. Let phone cool.

1:36 Primary 10SEH1729862177 4 bars 83% 
1:36 Crash at 10SEH1730162186 though see at 1:48. Short tracklog crash with no waypoints or photos taken in it. Edited to Damage Obs due to crash for contrast.
1:38 to 1:48 17 photos out of app
1:48 Bring QC to front and see orange screen. 3 bars, 79% Reopen workspace.
![20240705_083801_kj](https://github.com/pjdohertygis/SARCOP/assets/66851958/8dd28a87-cf9a-47d6-bdeb-2c22c97f79c6)

1:49 PM Primary End Time 2:16 PM crash at 10SEH1724362032 though see at 2:18.
1:49 ROE with photo in app 10SEH1738562152 one photo out of app.
1:51 2:16 Recorded 0:44 sec video has stutter / lag, 15 photos out of app. Several camera failures. Phone hot. QC overheating phone or QC and camera pics at same time?
2:13 PM local temperature 92 degrees 
2:18 Bring QC to front see orange screen. 3 bars, 69% Reopen workspace.
Primary edited to Damage Obs due to crash for contrast.
![20240705_085107_kj](https://github.com/pjdohertygis/SARCOP/assets/66851958/0db0c3b5-c19e-413d-ac5e-1e77ecd0dc19)

2:18 PM Primary 3 bars 69% End Time 2:20 PM change to
Hasty End Time 2:29 PM ok.

### Priority impact

p0 - not time sensitive

### Impact

Can't tell if it's crashing due to taking photos in and out of app, phone over heating, or other.
If need to take pics out of app or short pan area video clip to be sent via other for privacy, the phone got hot and had camera errors.

**Comment by pjdohertygis** [comment]
I sent a note to the QuickCapture for follow up @KeithJGw - I'll let you know what we hear.

**Comment by pjdohertygis** [comment]
For those that want to test, here is the example project https://experience.arcgis.com/experience/9051a07ffd1947bbb395e9f9b4088f85/page/Battlecard/

**Comment by pjdohertygis** [comment]
we are also tracking this https://r2.community.samsung.com/t5/Galaxy-A/Heating-problem-update-on-my-Galaxy-A53-5g/td-p/13506253

**Comment by jdokemaps** [comment]
Kevin Kay with NAPSG reported increased overheating on his Android  since the last Android update. He does not regularly use QuickCapture and had not used it at all during the reported overheating. 

Device Specifics:
Pixel 6 Pro
Android 14
Build AP2A.240605.024

**Comment by pjdohertygis** [comment]
@emontague-napsg  can you head over to the QuickCapture booth as well and raise this with them?

**Comment by KeithJGw** [comment]
Additional notes; More phone OS info: Google Play system update May 1, 2024
Baseband version A536USQSAEXF2
Kernel version 5.10.198-androis12-9-28577532-abA5
36USQSAEXF2
#1 Mon Jun 3 15:53;25 KST 2024
Build number UPA.231005.007.A536USQSAEXF2

Questions, answers, and suggestions for consideration from 7/10/2024 SARGeo meeting:
Statement: Sometimes defective batteries and processors cause overheating.
A: It is not a defective battery on this phone.
Q: Does the Samsung have a case on it? That could cause heat to trap.
A:  Negative, no case. Not in pocket or backpack. In vehicle cradle with AC on it enroute and on foot handheld at site.
Statement: Seems Samsung A53 has a processor overheat problem from old firmware.
A: Will look into that
[Paul added the Samsung forum link for the overheat issue here. Started in 2023 though there are a couple of 2024 entries. No mention of OS version or build.]
Statement: Try to stick any background apps into force quit mode then try again. It might be a background app.
Statement: Or bad app causing too much processor usage.
A: Maybe, though I used the same workflow of pics in and out of app several times without it overheating previously. Will look into that. I’ve gotten QuickCapture using too much memory notifications before.
Statement: (Paraphrased) Check if Alexa / Google home management apps are running. Commentor mentioned that they had an issue with one.
A: I do not have Alexa or Google nest or any home management app on my phone.

**Comment by KeithJGw** [comment]
After further testing, I believe this isn't a QuickCapture issue per se and moreso a device processor heat when using more than one app at the same time issue. While the heat dispersion of the processor and maybe a firmware thing might be going on, I was able to cause an over heat condition at other times using more than one app.
There's an increase in heat on app start up then tapers a bit then levels out. If you launch more than one app sequentially, the apps starting heat combines and can cause issues or starting a high processor use app/s when another is aready running.

**Comment by pjdohertygis** [comment]
Closing this for now unless it comes up again.
