### ISSUE TITLE
[BUG] -  QuickCapture auto-correct issue with RST 

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#285]
### Which app?

QuickCapture

### Describe the Device, Operating System, and Browser

iPad Mini

### Describe the bug

From Dave Weber 07/16 - b.	A iPad mini user had an issue with the auto correct when typing in NY in QC to try and auto populate NY-TF1 for the exercise.  It continually corrected the NY to My then he couldn’t proceed to the next screen.  Amazingly, this effectively locked him up.  He then had to type the NY-TF1 in every time as that was his TF for the exercise.  I simply had him disable the auto correct feature in the iOS to fix that one.  I felt sorry for him though.

### Expected Behavior

Pick from dropdown

### Reproduction Steps & Sample

Ask Dave Weber for more details.

### Priority impact

p0 - not time sensitive

### Impact

Inconvenient

**Comment by oviera-napsg** [comment]
Will attempt to recreate, however, iOS auto-correct is typically tied to the long-term behavior of the user across all device typing/keyboard use and not usually an application-specific problem.

**Comment by oviera-napsg** [comment]
No additional feedback or recreation issues.  Confirmed, for now, that auto-correct behavior is tied to the device keyboard settings and user behavior.  Advise future users to either select their intended text from the auto-correct options, or, if causing significant issues such as with the original reporting user, disable autocorrect suggestions in the devices keyboard/ text settings.
