### ISSUE TITLE
[BUG] - Edit widget not loading editable layers (Post-AGOL Release)

### ISSUE THREAD

**Issue by pjdohertygis** [pjdohertygis/SARCOP#312]
### Which app?

Intel Manager 2.0 (Experience Builder)

### Describe the Device, Operating System, and Browser

All Browsers, All OS

### Describe the bug

The Edit widget suddenly "lags" before showing that there are any editable layers. 

Watch video: 
[Recording 2024-11-13 132644.zip](https://github.com/user-attachments/files/17737574/Recording.2024-11-13.132644.zip)

### Expected Behavior

It should automatically show that layers are editable in the app. 

### Reproduction Steps & Sample

1. Go to https://experience.arcgis.com/experience/9051a07ffd1947bbb395e9f9b4088f85/page/Intel-Manager-2_0/
2. Click on the "Field Edit" Widget 
3. Wait for widget to load, check error console
4. After 5-10s it shows editable layers

### Other Relevant Info

I turned on tooltips, edit vertices by default. I can test turning these off to see if it is the cause of the behavior.

### Priority impact

Time Sensitive

### Impact

Users will be confused thinking the app is "broken".

**Comment by avezina** [comment]
An issue was submitted with the Experience Builder team.

**Comment by pjdohertygis** [comment]
This appears to be fixed! I'll reopen if it pops up anywhere else.
